using AStar.Dev.Source.Generators.ServiceRegistrationGeneration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace AStar.Dev.Source.Generators.Tests.Unit.ServiceRegistrationGeneration;

public class ServiceRegistrationGeneratorShould()
{
    private const string AttributeSource = @"using System;

namespace AStar.Dev.Source.Generators.Attributes
{
    public enum ServiceLifetime
    {
        Singleton,
        Scoped,
        Transient
    }

    [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
    public sealed class AutoRegisterServiceAttribute : Attribute
    {
        public AutoRegisterServiceAttribute(ServiceLifetime lifetime = ServiceLifetime.Scoped) { Lifetime = lifetime; }
        public ServiceLifetime Lifetime { get; }
        public Type? As { get; set; }
        public bool AsSelf { get; set; } = false;
    }
}
";

    private static CSharpCompilation CreateCompilation(string input)
    {
        var diReference = MetadataReference.CreateFromFile(typeof(Microsoft.Extensions.DependencyInjection.IServiceCollection).Assembly.Location);
        return CSharpCompilation.Create("TestAssembly",
            [
                CSharpSyntaxTree.ParseText(AttributeSource),
                CSharpSyntaxTree.ParseText(input)
            ],
            [
                MetadataReference.CreateFromFile(typeof(object).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(Attribute).Assembly.Location),
                MetadataReference.CreateFromFile(typeof(System.Runtime.AssemblyTargetedPatchBandAttribute).Assembly.Location),
                diReference
            ],
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    [Fact]
    public void RegisterClassWithSingleInterface_DefaultScoped()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    public interface IFoo { }

    [AutoRegisterService]
    public class Foo : IFoo { }
}
";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));
        generated.Equals(default(GeneratedSourceResult)).ShouldBeFalse();
        string text = generated.SourceText.ToString();

        text.ShouldBe(@"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;

namespace TestNamespace;

public static class GeneratedServiceCollectionExtensions
{
    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)
    {
        services.AddScoped<global::TestNamespace.IFoo, global::TestNamespace.Foo>();
        return services;
    }
}
");
    }

    [Fact]
    public void RegisterClassWithSingleInterface_SingletonLifetime()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    public interface IFoo { }

    [AutoRegisterService(ServiceLifetime.Singleton)]
    public class Foo : IFoo { }
}";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));
        generated.Equals(default(GeneratedSourceResult)).ShouldBeFalse();
        string text = generated.SourceText.ToString();

        text.ShouldBe(@"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;

namespace TestNamespace;

public static class GeneratedServiceCollectionExtensions
{
    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)
    {
        services.AddSingleton<global::TestNamespace.IFoo, global::TestNamespace.Foo>();
        return services;
    }
}
");
    }

    [Fact]
    public void RegisterClassWithSingleInterface_AsSelfTrue()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    public interface IFoo { }

    [AutoRegisterService(AsSelf = true)]
    public class Foo : IFoo { }
}";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));
        generated.Equals(default(GeneratedSourceResult)).ShouldBeFalse();
        string text = generated.SourceText.ToString();

        text.ShouldBe(@"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;

namespace TestNamespace;

public static class GeneratedServiceCollectionExtensions
{
    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)
    {
        services.AddScoped<global::TestNamespace.IFoo, global::TestNamespace.Foo>();
        services.AddScoped<global::TestNamespace.Foo>();
        return services;
    }
}
");
    }

    [Fact]
    public void RegisterClassWithTwoInterfaces_AsOverride()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    public interface IFoo { }

    public interface IBar { }

    [AutoRegisterService(As = typeof(IBar))]
    public class Foo : IFoo, IBar { }
}";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));
        generated.Equals(default(GeneratedSourceResult)).ShouldBeFalse();
        string text = generated.SourceText.ToString();

        text.ShouldBe(@"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;

namespace TestNamespace;

public static class GeneratedServiceCollectionExtensions
{
    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)
    {
        services.AddScoped<global::TestNamespace.IBar, global::TestNamespace.Foo>();
        return services;
    }
}
");
    }

    [Fact]
    public void RegisterClassWithNoInterface_AsSelfTrue()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    [AutoRegisterService(AsSelf = true)]
    public class Foo { }
}
";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));
        generated.Equals(default(GeneratedSourceResult)).ShouldBeFalse();
        string text = generated.SourceText.ToString();

        text.ShouldBe(@"// <auto-generated/>
using Microsoft.Extensions.DependencyInjection;

namespace TestNamespace;

public static class GeneratedServiceCollectionExtensions
{
    public static IServiceCollection AddAnnotatedServices(this IServiceCollection services)
    {
        services.AddScoped<global::TestNamespace.Foo>();
        return services;
    }
}
");
    }

    [Fact]
    public void DoesNotRegisterAbstractOrNonPublicOrGenericClasses()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;

namespace TestNamespace
{
    public interface IFoo { }

    [AutoRegisterService]
    public abstract class AbstractFoo : IFoo { }

    [AutoRegisterService] internal class InternalFoo : IFoo
    { }

    [AutoRegisterService]
    public class GenericFoo<T> : IFoo { }
}
";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));

        // All candidates are filtered out (abstract, internal, generic), so no source should be generated
        generated.Equals(default(GeneratedSourceResult)).ShouldBeTrue();
    }

    [Fact]
    public void DoesNotRegisterClassWithoutServiceAttribute()
    {
        const string input = @"namespace TestNamespace
{
    public interface IFoo { }

    public class Foo : IFoo { }
}";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));

        if(!generated.Equals(default(GeneratedSourceResult)))
        {
            string text = generated.SourceText.ToString();

            text.ShouldNotContain("Foo");
        }
    }

    [Fact]
    public void DoesNotRegisterClassWithMultipleInterfacesAndNoAsSpecified()
    {
        const string input = @"using AStar.Dev.Source.Generators.Attributes;
namespace TestNamespace
{
    public interface IFoo { }
    public interface IBar { }

    [AutoRegisterService]
    public class Foo : IFoo, IBar
    { }
}
";
        var compilation = CreateCompilation(input);
        var generator = new ServiceRegistrationGenerator();
        var driver = CSharpGeneratorDriver.Create(generator);
        driver = (CSharpGeneratorDriver)driver.RunGenerators(compilation, TestContext.Current.CancellationToken);
        var result = driver.GetRunResult();
        var generated = result.Results.SelectMany(r => r.GeneratedSources).FirstOrDefault(x => x.HintName.Contains("ServiceCollectionExtensions", StringComparison.Ordinal));

        if(!generated.Equals(default(GeneratedSourceResult)))
        {
            string text = generated.SourceText.ToString();

            text.ShouldNotContain("Foo");
        }
    }
}
