// <auto-generated />
using System;
using System.Collections.Generic;
using AStar.Dev.Infrastructure.AppDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.Infrastructure.AppDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621214637_Indexes")]
    partial class Indexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.Profile#AccountProfile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DisplayName");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quota", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.Quota#StorageQuota", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("TotalBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuotaTotal");

                            b1.Property<long>("UsedBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuotaUsed");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SyncConfig", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.SyncConfig#AccountSyncConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("ConflictPolicy")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ConflictPolicy");

                            b1.Property<string>("LocalSyncPath")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalSyncPath");
                        });

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncStartedAt")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("DriveStates");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFamous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("FileClassificationCategories");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncConflictEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetectedAt_Ticks");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LocalModified_Ticks");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncJobEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QueuedAt_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RemotePath")
                        .IsUnique();

                    b.ToTable("SyncRules");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("RemoteModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("LocalPath");

                    b.HasIndex("RemotePath");

                    b.HasIndex("SizeInBytes");

                    b.HasIndex("AccountId", "LocalPath");

                    b.HasIndex("AccountId", "RemoteItemId")
                        .IsUnique();

                    b.HasIndex("AccountId", "SizeInBytes");

                    b.ToTable("SyncedItems");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemFileClassificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncedItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SyncedItemId", "CategoryId")
                        .IsUnique();

                    b.ToTable("SyncedItemFileClassifications");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithOne()
                        .HasForeignKey("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncJobEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncRuleEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("AStar.Dev.Infrastructure.AppDb.Entities.VersionInfo", "Tags", b1 =>
                        {
                            b1.Property<int>("SyncedItemEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CTag")
                                .HasColumnType("TEXT")
                                .HasColumnName("CTag");

                            b1.Property<string>("ETag")
                                .HasColumnType("TEXT")
                                .HasColumnName("ETag");

                            b1.HasKey("SyncedItemEntityId");

                            b1.ToTable("SyncedItems");

                            b1.WithOwner()
                                .HasForeignKey("SyncedItemEntityId");
                        });

                    b.Navigation("Account");

                    b.Navigation("Tags")
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemFileClassificationEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemEntity", "SyncedItem")
                        .WithMany()
                        .HasForeignKey("SyncedItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SyncedItem");
                });
#pragma warning restore 612, 618
        }
    }
}
