// <auto-generated />
using System;
using System.Collections.Generic;
using AStar.Dev.Infrastructure.AppDb;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AStar.Dev.Infrastructure.AppDb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721065738_AddPriorityColumnToFileClassificationCategoryEntity")]
    partial class AddPriorityColumnToFileClassificationCategoryEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccentIndex")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSyncedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Profile", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.Profile#AccountProfile", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DisplayName");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Quota", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.Quota#StorageQuota", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("TotalBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuotaTotal");

                            b1.Property<long>("UsedBytes")
                                .HasColumnType("INTEGER")
                                .HasColumnName("QuotaUsed");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SyncConfig", "AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity.SyncConfig#AccountSyncConfig", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("ConflictPolicy")
                                .HasColumnType("INTEGER")
                                .HasColumnName("ConflictPolicy");

                            b1.Property<string>("LocalSyncPath")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("LocalSyncPath");
                        });

                    b.HasKey("Id");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.ConnectionStringsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<string>("Sqlite")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.ToTable("ConnectionStrings", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.DeletionStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HardDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("HardDeletePending_Ticks");

                    b.Property<long?>("SoftDeletePending")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeletePending_Ticks");

                    b.Property<long?>("SoftDeleted")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SoftDeleted_Ticks");

                    b.HasKey("Id");

                    b.ToTable("DeletionStatus", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<string>("DeltaLink")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastSyncStartedAt")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("DriveStates");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.EventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("DirectoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("EventOccurredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EventOccurredAt_Ticks");

                    b.Property<long>("FileCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FileCreated_Ticks");

                    b.Property<long>("FileLastModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("FileLastModified_Ticks");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Event", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileAccessDetailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DetailsLastUpdated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetailsLastUpdated_Ticks");

                    b.Property<long?>("LastViewed")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastViewed_Ticks");

                    b.Property<bool>("MoveRequired")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("FileAccessDetail", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFamous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("ParentId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique();

                    b.ToTable("FileClassificationCategories");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<Guid>("FileDetailId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("FileDetailId", "CategoryId")
                        .IsUnique();

                    b.ToTable("FileClassifications", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<int>("DeletionStatusId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileAccessDetailId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FileHandle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ImageDetailId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsImage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DirectoryName", "AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity.DirectoryName#DirectoryName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("DirectoryName");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "FileName", "AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity.FileName#FileName", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("FileName");
                        });

                    b.HasKey("Id");

                    b.HasIndex("DeletionStatusId");

                    b.HasIndex("FileAccessDetailId");

                    b.HasIndex("FileHandle")
                        .IsUnique();

                    b.HasIndex("FileSize");

                    b.HasIndex("ImageDetailId");

                    b.HasIndex("IsImage", "FileSize")
                        .HasDatabaseName("IX_FileDetail_DuplicateImages");

                    b.ToTable("FileDetail", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.ImageDetailEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ImageDetail", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.ModelToIgnoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.ToTable("ModelToIgnore", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.ScrapeDirectoriesEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseDirectory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseDirectoryFamous")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseSaveDirectory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<string>("RootDirectory")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SubDirectoryName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.ToTable("ScrapeDirectories", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.ScrapedTagEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Value")
                        .IsUnique();

                    b.ToTable("ScrapedTag", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SearchCategoryEntity", b =>
                {
                    b.Property<int>("SearchConfigurationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IncludeInSearch")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFamous")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsInternet")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastKnownImageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LastPageVisited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("SearchConfigurationId", "Id");

                    b.ToTable("SearchCategories", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SearchConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<int>("ImagePauseInSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LoginUrl")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchString")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchStringPrefix")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchStringSuffix")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<float?>("SlowMotionDelay")
                        .HasColumnType("REAL");

                    b.Property<int>("StartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subscriptions")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubscriptionsStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubscriptionsTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TopWallpapers")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<int>("TopWallpapersStartingPageNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TopWallpapersTotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPages")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<bool>("UseHeadless")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SearchConfiguration", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncConflictEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<long>("DetectedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DetectedAt_Ticks");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LocalModified_Ticks");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("LocalSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<long>("RemoteSize")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Resolution")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ResolvedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncConflicts");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncJobEntity", b =>
                {
                    b.Property<byte[]>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Direction")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FolderId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("QueuedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("QueuedAt_Ticks");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModified")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModified_Ticks");

                    b.Property<int>("State")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "State");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RuleType")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AccountId", "RemotePath")
                        .IsUnique();

                    b.ToTable("SyncRules");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<Guid?>("FileDetailId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsFolder")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteItemId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("RemoteModifiedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RemoteModifiedAt_Ticks");

                    b.Property<string>("RemoteParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemotePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.HasKey("Id");

                    b.HasIndex("FileDetailId");

                    b.HasIndex("LocalPath");

                    b.HasIndex("RemotePath");

                    b.HasIndex("SizeInBytes");

                    b.HasIndex("AccountId", "LocalPath");

                    b.HasIndex("AccountId", "RemoteItemId")
                        .IsUnique();

                    b.HasIndex("AccountId", "SizeInBytes");

                    b.HasIndex("AccountId", "IsFolder", "RemotePath");

                    b.HasIndex("AccountId", "IsFolder", "SizeInBytes");

                    b.ToTable("SyncedItems");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.TagToIgnoreEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<bool>("IgnoreImage")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.ToTable("TagToIgnore", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.UserConfigurationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAt_Ticks");

                    b.Property<string>("LoginEmailAddress")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionCookie")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAt_Ticks");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserConfiguration", (string)null);
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithOne()
                        .HasForeignKey("AStar.Dev.Infrastructure.AppDb.Entities.DriveStateEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileClassificationCategoryEntity", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("FileDetail");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.DeletionStatusEntity", "DeletionStatus")
                        .WithMany()
                        .HasForeignKey("DeletionStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileAccessDetailEntity", "FileAccessDetail")
                        .WithMany()
                        .HasForeignKey("FileAccessDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.ImageDetailEntity", "ImageDetail")
                        .WithMany()
                        .HasForeignKey("ImageDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeletionStatus");

                    b.Navigation("FileAccessDetail");

                    b.Navigation("ImageDetail");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SearchCategoryEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.SearchConfigurationEntity", "SearchConfiguration")
                        .WithMany("SearchCategories")
                        .HasForeignKey("SearchConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SearchConfiguration");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncConflictEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncJobEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncRuleEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SyncedItemEntity", b =>
                {
                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.AccountEntity", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AStar.Dev.Infrastructure.AppDb.Entities.FileDetailEntity", "FileDetail")
                        .WithMany()
                        .HasForeignKey("FileDetailId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.OwnsOne("AStar.Dev.Infrastructure.AppDb.ValueTypes.VersionInfo", "Tags", b1 =>
                        {
                            b1.Property<int>("SyncedItemEntityId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CTag")
                                .HasColumnType("TEXT")
                                .HasColumnName("CTag");

                            b1.Property<string>("ETag")
                                .HasColumnType("TEXT")
                                .HasColumnName("ETag");

                            b1.HasKey("SyncedItemEntityId");

                            b1.ToTable("SyncedItems");

                            b1.WithOwner()
                                .HasForeignKey("SyncedItemEntityId");
                        });

                    b.Navigation("Account");

                    b.Navigation("FileDetail");

                    b.Navigation("Tags")
                        .IsRequired();
                });

            modelBuilder.Entity("AStar.Dev.Infrastructure.AppDb.Entities.SearchConfigurationEntity", b =>
                {
                    b.Navigation("SearchCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
