using Microsoft.CodeAnalysis;

namespace AStar.Dev.Source.Generators.StrongIdCodeGeneration;

internal static class StrongIdCodeGenerator
{
    private const string AutoGeneratedComment = "// <auto-generated/>";
    private const string Usings = "using System;\nusing System.Collections.Generic;";

    public static string Generate(StrongIdModel model)
    {
        string ns = model.Namespace is null ? string.Empty : $"namespace {model.Namespace};";
        string accessibility = model.Accessibility == Accessibility.Internal ? "internal" : "public";
        string underlying = GetRequiredUnderlyingIdType(model);

        // Use string interpolation for code generation
        return $"{AutoGeneratedComment}\n\n{Usings}\n\n{(string.IsNullOrEmpty(ns) ? string.Empty : ns)}\n\n{accessibility} readonly partial record struct {model.ModelName}({underlying} Id);\n";
    }

    private static string GetRequiredUnderlyingIdType(StrongIdModel model)
    {
        string underlying = model.UnderlyingTypeDisplay;
        if(string.IsNullOrEmpty(underlying))
            return "System.Guid";

        if(underlying.IndexOf('.') < 0)
        {
            switch (underlying)
            {
                case "Guid":
                    underlying = "System.Guid";
                    break;
                case "string":
                    underlying = "System.String";
                    break;
                case "int":
                    underlying = "System.Int32";
                    break;
            }
        }

        return underlying;
    }
}
